"""
Brand palette for arXiv Digest.
Single source of truth — imported by digest.py, setup/app.py, and any future modules.
"""

# Also defined in setup/.streamlit/config.toml (Streamlit TOML can't import Python).
PINE = "#2F4F3E"
GOLD = "#EBC944"
UMBER = "#7A5A3A"
ASH_WHITE = "#F6F5F2"
ASH_BLACK = "#2B2B2B"
CARD_BORDER = "#D8D6D0"
WARM_GREY = "#6A6A66"
PINE_WASH = "#EDF2EF"
PINE_LIGHT = "#3D6B52"
GOLD_LIGHT = "#F5E08A"
GOLD_WASH = "#FFF8E1"
ALERT_RED = "#C0392B"
ALERT_RED_WASH = "#FFF0F0"
CHARCOAL = "#1F1F1F"
CATALOG_PURPLE = "#6B21A8"
CATALOG_WASH = "#F3E8FF"
FONT_HEADING = "'DM Serif Display', Georgia, serif"
FONT_BODY = "'IBM Plex Sans', Helvetica, Arial, sans-serif"
FONT_MONO = "'DM Mono', monospace"
