"""
Data constants for the arXiv Digest setup wizard.
Extracted from app.py to keep the wizard focused on UI logic.
"""
from __future__ import annotations

# ─────────────────────────────────────────────────────────────
#  Mini setup presets (no ORCID)
# ─────────────────────────────────────────────────────────────

ASTRO_MINI_TRACKS = {
    "general_astronomy": {
        "label": "General astronomy",
        "blurb": "A broad weekly round-up across the biggest astronomy categories.",
        "categories": [
            "astro-ph.EP",
            "astro-ph.SR",
            "astro-ph.GA",
            "astro-ph.CO",
            "astro-ph.HE",
            "astro-ph.IM",
        ],
        "keywords": {
            "astronomy": 8,
            "astrophysics": 8,
            "observations": 5,
            "survey": 5,
            "telescope": 4,
        },
    },
    "exoplanets": {
        "label": "Exoplanets",
        "blurb": "Planets, atmospheres, orbital architectures, and habitability.",
        "categories": ["astro-ph.EP"],
        "keywords": {
            "exoplanet": 10,
            "planet atmosphere": 8,
            "transit": 7,
            "radial velocity": 7,
            "habitability": 5,
            "JWST": 4,
        },
    },
    "stars": {
        "label": "Stars",
        "blurb": "Stellar physics, rotation, binaries, variability, and populations.",
        "categories": ["astro-ph.SR"],
        "keywords": {
            "stellar": 10,
            "stellar evolution": 8,
            "binary star": 7,
            "asteroseismology": 6,
            "rotation": 6,
            "spectroscopy": 5,
        },
    },
    "galaxies": {
        "label": "Galaxies",
        "blurb": "Galaxy formation, star formation, AGN, and the Milky Way.",
        "categories": ["astro-ph.GA"],
        "keywords": {
            "galaxy": 10,
            "milky way": 7,
            "star formation": 7,
            "AGN": 6,
            "dark matter": 6,
            "quasar": 5,
        },
    },
    "cosmology": {
        "label": "Cosmology",
        "blurb": "Large-scale structure, dark energy, inflation, and early-universe physics.",
        "categories": ["astro-ph.CO"],
        "keywords": {
            "cosmology": 10,
            "dark energy": 8,
            "inflation": 7,
            "CMB": 7,
            "large-scale structure": 7,
            "gravitational lensing": 5,
        },
    },
    "high_energy": {
        "label": "High-energy astrophysics",
        "blurb": "Black holes, neutron stars, transients, and compact objects.",
        "categories": ["astro-ph.HE"],
        "keywords": {
            "black hole": 9,
            "neutron star": 8,
            "supernova": 7,
            "gamma-ray": 6,
            "X-ray": 6,
            "gravitational wave": 6,
        },
    },
    "instrumentation": {
        "label": "Instrumentation",
        "blurb": "Telescopes, detectors, surveys, pipelines, and observing methods.",
        "categories": ["astro-ph.IM"],
        "keywords": {
            "instrumentation": 9,
            "telescope": 8,
            "detector": 7,
            "survey": 6,
            "pipeline": 6,
            "calibration": 5,
        },
    },
    "solar_helio": {
        "label": "Solar & heliophysics",
        "blurb": "Solar physics, space weather, heliosphere, and asteroseismology.",
        "categories": ["astro-ph.SR"],
        "keywords": {
            "solar": 9,
            "heliosphere": 8,
            "space weather": 7,
            "coronal": 6,
            "solar wind": 6,
            "sunspot": 5,
        },
    },
    "methods_ml": {
        "label": "Methods & machine learning",
        "blurb": "Statistical methods, machine learning, and data science for astronomy.",
        "categories": ["astro-ph.IM", "stat.ML"],
        "keywords": {
            "machine learning": 9,
            "neural network": 8,
            "Bayesian": 7,
            "classification": 6,
            "deep learning": 6,
            "data science": 5,
        },
    },
}

AU_STUDENT_TRACK_LABELS = {
    "au_astronomy": "AU Astronomy",
    "stars": "Stars",
    "galaxies": "Galaxies",
    "cosmology": "Cosmology",
    "exoplanets": "Planets + exoplanets",
    "high_energy": "High-energy astrophysics",
    "instrumentation": "Instrumentation",
    "solar_helio": "Solar & heliophysics",
    "methods_ml": "Methods & machine learning",
}
AU_STUDENT_ALWAYS_TAG = "AU Astronomy"

AU_ASTRONOMY_PEOPLE = [
    {
        "name": "Simon Albrecht",
        "match": ["Albrecht, S", "Simon Albrecht"],
        "note": "Professor; teaches Exoplanets, Astrophysics, and Space Missions.",
    },
    {
        "name": "Mia Sloth Lundkvist",
        "match": ["Lundkvist, M", "Mia Sloth Lundkvist", "Mia S Lundkvist"],
        "note": "Associate professor; teaches Stars and planets.",
    },
    {
        "name": "Frank Grundahl",
        "match": ["Grundahl, F", "Frank Grundahl"],
        "note": "Professor; teaches Observational astrophysics and Intro to galaxies.",
    },
    {
        "name": "Karsten Brogaard",
        "match": ["Brogaard, K", "Karsten Brogaard", "Karsten Frank Brogaard"],
        "note": "Associate professor; teaches Exoplanets and Astrophysics.",
    },
    {
        "name": "Mikkel Norup Lund",
        "match": ["Lund, M", "Mikkel N Lund", "Mikkel Norup Lund", "Mikkel Norup"],
        "note": "Associate professor; teaches Asteroseismology and Experimental methods in astrophysics.",
    },
    {
        "name": "Hans Kjeldsen",
        "match": ["Kjeldsen, H", "Hans Kjeldsen"],
        "note": "Professor; stellar astrophysics, exoplanets, and Aarhus space instrumentation.",
    },
    {
        "name": "Christoffer Karoff",
        "match": ["Karoff, C", "Christoffer Karoff"],
        "note": "Professor; solar activity, student satellites, and Earth-observation space science.",
    },
    {
        "name": "Mads Fredslund Andersen",
        "match": [
            "Fredslund Andersen, M",
            "Mads Fredslund Andersen",
            "Mads F Andersen",
        ],
        "note": "Associate professor; SONG telescope, astronomical instrumentation, and student space projects.",
    },
]

AU_STUDENT_TELESCOPE_KEYWORDS = {
    "SONG": 9,
    "SONG telescope": 9,
    "Ole Romer Observatory": 8,
    "FUT": 8,
    "FUT telescope": 8,
    "Nordic Optical Telescope": 7,
    "FIES": 6,
    "student satellite": 7,
    "Delphini-1": 8,
    "AUSAT": 6,
    "data release": 6,
    "review": 6,
    "survey": 5,
    "catalog": 5,
}

AU_STUDENT_KEYWORD_ALIASES = {
    "SONG": ["Stellar Observations Network Group"],
    "Ole Romer Observatory": ["Ole Rømer Observatory"],
    "FUT": ["FUTeleskop", "Foreningen af Unge Fysikere Telescope"],
    "Nordic Optical Telescope": ["NOT telescope"],
    "student satellite": ["student space mission", "student space program"],
    "review": ["review article", "topical review"],
    "catalog": ["catalogue"],
}

# ─────────────────────────────────────────────────────────────
#  arXiv categories + AI suggestion hints
# ─────────────────────────────────────────────────────────────

ARXIV_CATEGORIES = {
    # Astrophysics
    "astro-ph.EP": "Earth and Planetary Astrophysics",
    "astro-ph.SR": "Solar and Stellar Astrophysics",
    "astro-ph.GA": "Astrophysics of Galaxies",
    "astro-ph.CO": "Cosmology and Nongalactic Astrophysics",
    "astro-ph.HE": "High Energy Astrophysical Phenomena",
    "astro-ph.IM": "Instrumentation and Methods",
    # Condensed Matter
    "cond-mat.dis-nn": "Disordered Systems and Neural Networks",
    "cond-mat.mes-hall": "Mesoscale and Nanoscale Physics",
    "cond-mat.mtrl-sci": "Materials Science",
    "cond-mat.other": "Other Condensed Matter",
    "cond-mat.quant-gas": "Quantum Gases",
    "cond-mat.soft": "Soft Condensed Matter",
    "cond-mat.stat-mech": "Statistical Mechanics",
    "cond-mat.str-el": "Strongly Correlated Electrons",
    "cond-mat.supr-con": "Superconductivity",
    # General Relativity & Quantum Cosmology
    "gr-qc": "General Relativity and Quantum Cosmology",
    # High Energy Physics
    "hep-ex": "High Energy Physics — Experiment",
    "hep-lat": "High Energy Physics — Lattice",
    "hep-ph": "High Energy Physics — Phenomenology",
    "hep-th": "High Energy Physics — Theory",
    # Mathematical Physics
    "math-ph": "Mathematical Physics",
    # Nonlinear Sciences
    "nlin.AO": "Adaptation and Self-Organizing Systems",
    "nlin.CD": "Chaotic Dynamics",
    "nlin.CG": "Cellular Automata and Lattice Gases",
    "nlin.PS": "Pattern Formation and Solitons",
    "nlin.SI": "Exactly Solvable and Integrable Systems",
    # Nuclear
    "nucl-ex": "Nuclear Experiment",
    "nucl-th": "Nuclear Theory",
    # Physics
    "physics.acc-ph": "Accelerator Physics",
    "physics.ao-ph": "Atmospheric and Oceanic Physics",
    "physics.atom-ph": "Atomic Physics",
    "physics.atm-clus": "Atomic and Molecular Clusters",
    "physics.bio-ph": "Biological Physics",
    "physics.chem-ph": "Chemical Physics",
    "physics.class-ph": "Classical Physics",
    "physics.comp-ph": "Computational Physics",
    "physics.data-an": "Data Analysis, Statistics and Probability",
    "physics.ed-ph": "Physics Education",
    "physics.flu-dyn": "Fluid Dynamics",
    "physics.gen-ph": "General Physics",
    "physics.geo-ph": "Geophysics",
    "physics.hist-ph": "History and Philosophy of Physics",
    "physics.ins-det": "Instrumentation and Detectors",
    "physics.med-ph": "Medical Physics",
    "physics.optics": "Optics",
    "physics.plasm-ph": "Plasma Physics",
    "physics.pop-ph": "Popular Physics",
    "physics.soc-ph": "Physics and Society",
    "physics.space-ph": "Space Physics",
    # Quantum Physics
    "quant-ph": "Quantum Physics",
    # Computer Science
    "cs.AI": "Artificial Intelligence",
    "cs.CL": "Computation and Language (NLP)",
    "cs.CV": "Computer Vision",
    "cs.DS": "Data Structures and Algorithms",
    "cs.LG": "Machine Learning",
    "cs.NE": "Neural and Evolutionary Computing",
    "cs.RO": "Robotics",
    # Mathematics
    "math.AG": "Algebraic Geometry",
    "math.AP": "Analysis of PDEs",
    "math.DG": "Differential Geometry",
    "math.DS": "Dynamical Systems",
    "math.NT": "Number Theory",
    "math.PR": "Probability",
    "math.ST": "Statistics Theory",
    # Statistics
    "stat.AP": "Applications (Statistics)",
    "stat.CO": "Computation (Statistics)",
    "stat.ME": "Methodology (Statistics)",
    "stat.ML": "Machine Learning (Statistics)",
    "stat.TH": "Statistics Theory",
    # Electrical Engineering
    "eess.AS": "Audio and Speech Processing",
    "eess.IV": "Image and Video Processing",
    "eess.SP": "Signal Processing",
    "eess.SY": "Systems and Control",
    # Quantitative Biology
    "q-bio.BM": "Biomolecules",
    "q-bio.CB": "Cell Behavior",
    "q-bio.GN": "Genomics",
    "q-bio.NC": "Neurons and Cognition",
    "q-bio.PE": "Populations and Evolution",
    "q-bio.QM": "Quantitative Methods",
}

# Hierarchical grouping for the category picker UI
ARXIV_GROUPS = {
    "Astrophysics": [
        "astro-ph.EP",
        "astro-ph.SR",
        "astro-ph.GA",
        "astro-ph.CO",
        "astro-ph.HE",
        "astro-ph.IM",
    ],
    "Condensed Matter": [
        "cond-mat.dis-nn",
        "cond-mat.mes-hall",
        "cond-mat.mtrl-sci",
        "cond-mat.other",
        "cond-mat.quant-gas",
        "cond-mat.soft",
        "cond-mat.stat-mech",
        "cond-mat.str-el",
        "cond-mat.supr-con",
    ],
    "General Relativity & Quantum Cosmology": ["gr-qc"],
    "High Energy Physics": ["hep-ex", "hep-lat", "hep-ph", "hep-th"],
    "Mathematical Physics": ["math-ph"],
    "Nonlinear Sciences": ["nlin.AO", "nlin.CD", "nlin.CG", "nlin.PS", "nlin.SI"],
    "Nuclear Physics": ["nucl-ex", "nucl-th"],
    "Physics": [
        "physics.acc-ph",
        "physics.ao-ph",
        "physics.atom-ph",
        "physics.atm-clus",
        "physics.bio-ph",
        "physics.chem-ph",
        "physics.class-ph",
        "physics.comp-ph",
        "physics.data-an",
        "physics.ed-ph",
        "physics.flu-dyn",
        "physics.gen-ph",
        "physics.geo-ph",
        "physics.hist-ph",
        "physics.ins-det",
        "physics.med-ph",
        "physics.optics",
        "physics.plasm-ph",
        "physics.pop-ph",
        "physics.soc-ph",
        "physics.space-ph",
    ],
    "Quantum Physics": ["quant-ph"],
    "Computer Science": ["cs.AI", "cs.CL", "cs.CV", "cs.DS", "cs.LG", "cs.NE", "cs.RO"],
    "Mathematics": [
        "math.AG",
        "math.AP",
        "math.DG",
        "math.DS",
        "math.NT",
        "math.PR",
        "math.ST",
    ],
    "Statistics": ["stat.AP", "stat.CO", "stat.ME", "stat.ML", "stat.TH"],
    "Electrical Engineering": ["eess.AS", "eess.IV", "eess.SP", "eess.SY"],
    "Quantitative Biology": [
        "q-bio.BM",
        "q-bio.CB",
        "q-bio.GN",
        "q-bio.NC",
        "q-bio.PE",
        "q-bio.QM",
    ],
}

# "Include if" hints — shown inside each group expander
ARXIV_GROUP_HINTS = {
    "Astrophysics": "You study stars, planets, galaxies, or cosmic phenomena.",
    "Condensed Matter": "You study materials, superconductors, or quantum systems in matter.",
    "General Relativity & Quantum Cosmology": "You work on spacetime, black holes, or gravitational waves.",
    "High Energy Physics": "You work on particles, colliders, or fundamental field theory.",
    "Mathematical Physics": "You bridge rigorous mathematics and physical theory.",
    "Nonlinear Sciences": "You study chaos, complex systems, or emergent patterns.",
    "Nuclear Physics": "You study atomic nuclei, nuclear reactions, or related theory.",
    "Physics": "You work in applied or specialized sub-fields of physics.",
    "Quantum Physics": "You work on quantum information, computing, or quantum optics.",
    "Computer Science": "You use or develop AI, ML, NLP, vision, or robotics methods.",
    "Mathematics": "You work in pure or applied mathematics.",
    "Statistics": "You work on statistical methods, ML theory, or data analysis.",
    "Electrical Engineering": "You process signals, audio, images, or design control systems.",
    "Quantitative Biology": "You apply quantitative methods to biological systems.",
}

# Terms that hint at which arXiv categories to suggest
CATEGORY_HINTS = {
    "astro-ph.EP": [
        "exoplanet",
        "planet formation",
        "transit",
        "radial velocity",
        "habitable",
        "atmosphere",
        "JWST",
        "Kepler",
        "TESS",
        "circumbinary",
        "hot jupiter",
        "sub-neptune",
        "super-earth",
        "protoplanetary",
        "protoplanetary disk",
        "planetary system",
        "planet formation",
        "transmission spectroscopy",
        "radial-velocity",
        "earth-like",
        "biosignature",
        "accretion disk",
    ],
    "astro-ph.SR": [
        "stellar",
        "stellar rotation",
        "binary star",
        "spectroscopy",
        "magnetic",
        "angular momentum",
        "obliquity",
        "spin-orbit",
        "vsini",
        "vbroad",
        "Gaia",
        "gyrochronology",
        "asteroseismology",
        "variable star",
        "pulsation",
        "white dwarf",
        "red giant",
        "main sequence",
        "chromosphere",
        "flare",
        "metallicity",
        "abundance",
        "spectral type",
        "eclipsing binary",
        "Rossiter-McLaughlin",
        "Doppler tomography",
        "Kraft break",
    ],
    "astro-ph.GA": [
        "galaxy",
        "galaxies",
        "galactic",
        "Milky Way",
        "dark matter",
        "interstellar",
        "ISM",
        "star formation",
        "AGN",
        "quasar",
        "merger",
        "cluster",
        "halo",
        "bulge",
        "spiral",
        "elliptical",
        "HII region",
        "nebula",
        "chemical evolution",
        "stellar population",
    ],
    "astro-ph.CO": [
        "cosmolog",
        "CMB",
        "dark energy",
        "inflation",
        "baryon",
        "large-scale structure",
        "BAO",
        "Hubble",
        "redshift",
        "gravitational lensing",
        "cosmic microwave",
        "primordial",
        "Big Bang",
        "expansion",
    ],
    "astro-ph.HE": [
        "black hole",
        "neutron star",
        "pulsar",
        "magnetar",
        "GRB",
        "gamma-ray",
        "X-ray",
        "accretion",
        "relativistic jet",
        "relativistic",
        "gravitational wave",
        "LIGO",
        "compact object",
        "supernova",
    ],
    "astro-ph.IM": [
        "instrument",
        "detector",
        "telescope",
        "survey",
        "pipeline",
        "calibration",
        "photometry",
        "astrometry",
        "spectrograph",
        "adaptive optics",
        "CCD",
        "coronagraph",
        "interferometry",
    ],
    "hep-th": [
        "string theory",
        "quantum field theory",
        "supersymmetry",
        "AdS/CFT",
        "holograph",
        "conformal field",
        "gauge theory",
        "brane",
        "S-matrix",
        "amplitude",
        "duality",
        "topological field theory",
    ],
    "hep-ph": [
        "particle physics",
        "Standard Model",
        "Higgs",
        "collider",
        "LHC",
        "neutrino",
        "dark matter candidate",
        "beyond Standard Model",
        "parton",
        "QCD",
        "electroweak",
        "flavor physics",
        "CP violation",
    ],
    "hep-ex": [
        "collider experiment",
        "ATLAS",
        "CMS",
        "LHCb",
        "Belle",
        "BaBar",
        "particle detector",
        "particle beam",
        "cross section measurement",
        "high energy experiment",
        "calorimeter",
    ],
    "hep-lat": [
        "lattice QCD",
        "lattice gauge",
        "Monte Carlo lattice",
        "Wilson fermion",
        "lattice field theory",
        "non-perturbative QCD",
    ],
    "gr-qc": [
        "general relativity",
        "gravitational wave",
        "black hole",
        "spacetime",
        "metric",
        "Einstein",
        "curvature",
        "singularity",
        "LIGO",
        "post-Newtonian",
        "numerical relativity",
        "wormhole",
        "geodesic",
    ],
    "math-ph": [
        "mathematical physics",
        "rigorous",
        "spectral theory",
        "operator algebra",
        "integrable system",
        "Hamiltonian",
        "symplectic",
        "functional analysis",
    ],
    "nucl-th": [
        "nuclear theory",
        "nuclear structure",
        "shell model",
        "nuclear force",
        "nucleon",
        "hadronic",
        "quark-gluon plasma",
        "nuclear matter",
        "fission",
    ],
    "nucl-ex": [
        "nuclear experiment",
        "nuclear reaction",
        "radioactive beam",
        "heavy-ion",
        "nuclear decay",
        "nuclear spectroscopy",
        "CERN",
        "RHIC",
        "nuclear cross section",
    ],
    "nlin.CD": [
        "chaos",
        "chaotic dynamics",
        "Lyapunov",
        "strange attractor",
        "bifurcation",
        "nonlinear dynamics",
        "sensitive dependence",
    ],
    "nlin.PS": [
        "soliton",
        "pattern formation",
        "nonlinear wave",
        "reaction-diffusion",
        "Turing pattern",
        "amplitude equation",
        "modulational instability",
    ],
    "nlin.SI": [
        "integrable",
        "inverse scattering",
        "Lax pair",
        "Painlevé",
        "exact solution",
        "conservation law",
        "Bäcklund",
    ],
    "nlin.AO": [
        "self-organization",
        "adaptation",
        "complex system",
        "emergence",
        "network dynamics",
        "synchronization",
    ],
    "cond-mat.supr-con": [
        "superconductor",
        "superconductivity",
        "BCS",
        "Cooper pair",
        "vortex",
        "Josephson",
        "pairing",
        "Tc",
        "Meissner",
        "flux",
    ],
    "cond-mat.str-el": [
        "strongly correlated",
        "Mott insulator",
        "Hubbard",
        "Kondo",
        "heavy fermion",
        "correlated electron",
        "charge order",
        "orbital order",
        "spin liquid",
        "Wigner",
    ],
    "cond-mat.mes-hall": [
        "quantum dot",
        "quantum well",
        "nanostructure",
        "mesoscopic",
        "Hall effect",
        "edge state",
        "nanowire",
        "carbon nanotube",
        "graphene",
        "2D material",
        "topological insulator",
        "Dirac",
        "Weyl",
        "quantum transport",
        "spintronics",
    ],
    "cond-mat.mtrl-sci": [
        "material",
        "thin film",
        "alloy",
        "doping",
        "defect",
        "grain boundary",
        "first-principles",
        "DFT",
        "density functional",
        "ab initio",
        "crystal structure",
        "X-ray diffraction",
        "XRD",
        "synthesis",
        "epitaxy",
        "heterostructure",
    ],
    "cond-mat.stat-mech": [
        "statistical mechanics",
        "phase transition",
        "critical exponent",
        "renormalization",
        "Ising model",
        "Monte Carlo",
        "entropy",
        "free energy",
        "thermodynamic",
        "universality",
        "scaling",
        "order parameter",
    ],
    "cond-mat.soft": [
        "soft matter",
        "polymer",
        "colloid",
        "liquid crystal",
        "gel",
        "foam",
        "active matter",
        "self-assembly",
        "rheology",
        "viscoelastic",
        "amphiphile",
    ],
    "cond-mat.quant-gas": [
        "ultracold",
        "Bose-Einstein condensate",
        "BEC",
        "optical lattice",
        "cold atom",
        "Fermi gas",
        "Feshbach resonance",
        "superfluidity",
        "quantum gas",
    ],
    "cond-mat.dis-nn": [
        "disorder",
        "Anderson localization",
        "spin glass",
        "random",
        "amorphous",
        "percolation",
        "neural network",
        "glassy",
        "many-body localization",
        "MBL",
    ],
    "quant-ph": [
        "quantum computing",
        "qubit",
        "entanglement",
        "quantum information",
        "quantum optics",
        "decoherence",
        "quantum error",
        "quantum algorithm",
    ],
    "physics.atom-ph": [
        "atomic physics",
        "cold atoms",
        "laser cooling",
        "Bose-Einstein",
        "ion trap",
        "optical clock",
        "precision measurement",
        "atomic spectrum",
        "photoionization",
    ],
    "physics.atm-clus": [
        "atomic cluster",
        "nanoparticle",
        "fullerene",
        "cluster physics",
        "molecular cluster",
        "van der Waals cluster",
    ],
    "physics.chem-ph": [
        "chemical physics",
        "molecular physics",
        "reaction dynamics",
        "potential energy surface",
        "spectroscopy",
        "photochemistry",
        "adiabatic",
        "Born-Oppenheimer",
    ],
    "physics.comp-ph": [
        "computational physics",
        "simulation",
        "numerical method",
        "finite element",
        "molecular dynamics simulation",
        "Monte Carlo simulation",
        "FDTD",
        "algorithm",
    ],
    "physics.plasm-ph": [
        "plasma",
        "fusion",
        "tokamak",
        "plasma wave",
        "magnetohydrodynamic",
        "MHD",
        "inertial confinement",
        "plasma instability",
        "ITER",
        "laser plasma",
    ],
    "physics.space-ph": [
        "space physics",
        "solar wind",
        "magnetosphere",
        "ionosphere",
        "cosmic ray",
        "heliosphere",
        "aurora",
        "geomagnetic storm",
        "Van Allen",
    ],
    "physics.ao-ph": [
        "atmospheric",
        "climate",
        "ocean",
        "meteorology",
        "geophysical fluid",
        "El Niño",
        "general circulation",
        "aerosol",
        "cloud physics",
    ],
    "physics.geo-ph": [
        "geophysics",
        "seismic",
        "earthquake",
        "mantle",
        "plate tectonics",
        "seismology",
        "geodesy",
        "geodynamics",
        "geomagnetism",
    ],
    "physics.ins-det": [
        "detector",
        "instrumentation",
        "sensor",
        "readout",
        "signal processing",
        "particle detector",
        "scintillator",
        "photodetector",
        "FPGA",
    ],
    "physics.med-ph": [
        "medical physics",
        "radiation therapy",
        "MRI",
        "CT scan",
        "dosimetry",
        "radiobiology",
        "proton therapy",
        "nuclear medicine",
        "imaging",
    ],
    "physics.optics": [
        "optical",
        "laser",
        "photon",
        "waveguide",
        "fiber",
        "lens",
        "diffraction",
        "nonlinear optics",
        "ultrafast",
        "plasmon",
    ],
    "physics.bio-ph": [
        "biophysics",
        "protein",
        "membrane",
        "DNA",
        "RNA",
        "cell",
        "molecular dynamics",
        "biological",
        "enzyme",
        "single-molecule",
    ],
    "physics.flu-dyn": [
        "fluid",
        "turbulence",
        "Navier-Stokes",
        "flow",
        "viscous",
        "Reynolds",
        "boundary layer",
        "vortex",
        "aerodynamics",
    ],
    "physics.acc-ph": [
        "accelerator",
        "synchrotron",
        "free electron laser",
        "beam physics",
        "particle accelerator",
        "storage ring",
        "undulator",
        "linac",
    ],
    "physics.data-an": [
        "data analysis",
        "statistical method",
        "uncertainty quantification",
        "systematic error",
        "likelihood",
        "goodness of fit",
    ],
    "cs.AI": [
        "artificial intelligence",
        "reasoning",
        "planning",
        "knowledge",
        "agent",
        "reinforcement learning",
        "multi-agent",
    ],
    "cs.LG": [
        "machine learning",
        "deep learning",
        "neural network",
        "transformer",
        "GPT",
        "training",
        "gradient",
        "optimization",
        "generalization",
    ],
    "cs.CV": [
        "computer vision",
        "image",
        "object detection",
        "segmentation",
        "convolutional",
        "CNN",
        "visual",
        "recognition",
    ],
    "cs.CL": [
        "natural language",
        "NLP",
        "language model",
        "text",
        "translation",
        "sentiment",
        "parsing",
        "BERT",
        "tokeniz",
    ],
    "cs.DS": [
        "algorithm",
        "data structure",
        "complexity",
        "graph algorithm",
        "sorting",
        "combinatorial",
        "approximation algorithm",
    ],
    "cs.RO": [
        "robot",
        "robotics",
        "motion planning",
        "control",
        "autonomous",
        "SLAM",
        "manipulation",
        "drone",
    ],
    "cs.NE": [
        "evolutionary",
        "genetic algorithm",
        "swarm",
        "neuroevolution",
        "neural architecture search",
        "bio-inspired",
    ],
    "math.AP": [
        "partial differential equation",
        "PDE",
        "elliptic",
        "parabolic",
        "hyperbolic",
        "weak solution",
        "regularity",
        "Sobolev",
    ],
    "math.PR": [
        "probability",
        "stochastic process",
        "Brownian motion",
        "Markov chain",
        "random walk",
        "martingale",
        "diffusion process",
    ],
    "math.ST": [
        "statistics",
        "hypothesis testing",
        "estimator",
        "asymptotic",
        "consistency",
        "maximum likelihood",
        "nonparametric",
    ],
    "math.DS": [
        "dynamical system",
        "ergodic",
        "attractor",
        "invariant measure",
        "topological dynamics",
        "symbolic dynamics",
    ],
    "math.NT": [
        "number theory",
        "prime",
        "Riemann",
        "arithmetic",
        "Diophantine",
        "algebraic number",
        "modular form",
        "L-function",
    ],
    "math.AG": [
        "algebraic geometry",
        "variety",
        "scheme",
        "sheaf",
        "cohomology",
        "moduli",
        "Hodge theory",
        "Calabi-Yau",
    ],
    "math.DG": [
        "differential geometry",
        "manifold",
        "Riemannian",
        "curvature tensor",
        "connection",
        "fiber bundle",
        "symplectic manifold",
    ],
    "math-ph": [
        "mathematical physics",
        "rigorous",
        "spectral theory",
        "operator algebra",
        "integrable system",
        "Hamiltonian",
        "symplectic",
    ],
    "stat.ML": [
        "statistical learning",
        "Bayesian",
        "inference",
        "regression",
        "classification",
        "kernel",
        "non-parametric",
        "MCMC",
    ],
    "stat.ME": [
        "statistical methodology",
        "survey sampling",
        "experimental design",
        "causal inference",
        "missing data",
        "mixed model",
    ],
    "stat.AP": [
        "applied statistics",
        "biostatistics",
        "clinical trial",
        "survival analysis",
        "epidemiology",
        "econometrics",
    ],
    "eess.SP": [
        "signal processing",
        "Fourier",
        "filter",
        "time series",
        "spectral estimation",
        "compressed sensing",
        "wavelet",
    ],
    "eess.SY": [
        "control system",
        "feedback",
        "stability",
        "optimal control",
        "robust control",
        "system identification",
        "Lyapunov",
    ],
    "eess.IV": [
        "image processing",
        "video",
        "compression",
        "super-resolution",
        "image reconstruction",
        "denoising",
    ],
    "eess.AS": [
        "audio",
        "speech recognition",
        "speaker",
        "acoustic",
        "sound",
        "music information retrieval",
        "spoken language",
    ],
    "q-bio.BM": [
        "biomolecule",
        "protein structure",
        "protein folding",
        "molecular biology",
        "enzyme kinetics",
        "RNA structure",
        "AlphaFold",
    ],
    "q-bio.NC": [
        "neuroscience",
        "neural circuit",
        "brain",
        "synapse",
        "spike",
        "neural coding",
        "cortex",
        "connectome",
    ],
    "q-bio.PE": [
        "evolution",
        "population genetics",
        "phylogeny",
        "fitness",
        "selection",
        "mutation rate",
        "ecological dynamics",
    ],
    "q-bio.GN": [
        "genomics",
        "genome",
        "gene expression",
        "RNA-seq",
        "CRISPR",
        "sequencing",
        "transcriptome",
        "epigenome",
    ],
    "q-bio.QM": [
        "quantitative biology",
        "mathematical biology",
        "systems biology",
        "computational biology",
        "bioinformatics",
    ],
    "q-bio.CB": [
        "cell motility",
        "cell signaling",
        "cytoskeleton",
        "cell division",
        "chemotaxis",
        "collective cell migration",
        "cellular mechanics",
    ],
    "stat.CO": [
        "computational statistics",
        "MCMC algorithm",
        "variational inference",
        "approximate Bayesian",
        "ABC",
        "expectation maximization",
    ],
    "stat.TH": [
        "statistical theory",
        "minimax",
        "risk bound",
        "concentration inequality",
        "semiparametric",
        "empirical process",
        "decision theory",
    ],
    "nlin.CG": [
        "cellular automaton",
        "lattice gas",
        "rule",
        "automata",
        "discrete simulation",
    ],
    "physics.soc-ph": [
        "social physics",
        "opinion dynamics",
        "social network",
        "agent-based social",
        "econophysics",
        "complex network",
    ],
}
